Fix dash containing name treatment

diff --git a/bin/miso-init b/bin/miso-init
--- a/bin/miso-init
+++ b/bin/miso-init
@@ -29,6 +29,18 @@ force=0
 target_dir=""
 positional_count=0
 
+set_target_dir() {
+  positional_count=$((positional_count + 1))
+  if [ "$positional_count" -gt 1 ]; then
+    echo "error: too many arguments" >&2
+    echo >&2
+    show_help >&2
+    exit 1
+  fi
+
+  target_dir="$1"
+}
+
 while [ "$#" -gt 0 ]; do
   case "$1" in
     -h|--help)
@@ -41,7 +53,10 @@ while [ "$#" -gt 0 ]; do
       ;;
     --)
       shift
-      break
+      while [ "$#" -gt 0 ]; do
+        set_target_dir "$1"
+        shift
+      done
       ;;
     -*)
       echo "error: unknown option: $1" >&2
@@ -50,14 +65,7 @@ while [ "$#" -gt 0 ]; do
       exit 1
       ;;
     *)
-      positional_count=$((positional_count + 1))
-      if [ "$positional_count" -gt 1 ]; then
-        echo "error: too many arguments" >&2
-        echo >&2
-        show_help >&2
-        exit 1
-      fi
-      target_dir="$1"
+      set_target_dir "$1"
       shift
       ;;
   esac
